apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: notification-webhook
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: notification-webhook-configmap
    files:
      - notification-webhook.ini=notification-webhook.ini