apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: synapse
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
  - pvc.yaml
configMapGenerator:
  - name: synapse-configmap
    files:
      - homeserver.yaml=homeserver.yaml
      - log.config=log.config
      - signing.key=signing.key