apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synapse-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-hostpath-hdd
  resources:
    requests:
      storage: 50Gi