---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sonarqube
      version: "1.2.1+162"
      sourceRef:
        kind: HelmRepository
        name: sonarqube
  valuesFrom:
    - kind: ConfigMap
      name: sonarqube-values
  interval: 1h0m0s
  releaseName: sonarqube
  targetNamespace: sonarqube

