---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: drone
  namespace: flux-system
spec:
  chart:
    spec:
      chart: drone
      version: "0.1.7"
      sourceRef:
        kind: HelmRepository
        name: drone
  valuesFrom:
    - kind: ConfigMap
      name: drone-values
  interval: 1h0m0s
  releaseName: drone
  targetNamespace: drone

