apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: jenkins
resources:
  - deployment.yaml
  - ingress.yaml
  - pvc.yaml
  - service.yaml
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - serviceaccount.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: docker-config-json
  type: kubernetes.io/dockerconfigjson
  files:
    - .dockerconfigjson=docker.json