---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  chart:
    spec:
      chart: metallb
      version: "0.11.0"
      sourceRef:
        kind: HelmRepository
        name: metallb
  valuesFrom:
    - kind: ConfigMap
      name: metallb-values
  interval: 1h0m0s
  releaseName: metallb
  targetNamespace: metallb

